# Create StorageClass for provisioning EOS automount volumes,
# and a PersistentVolumeClaim that's fulfilled by the StorageClass.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eos
provisioner: eosxd.csi.cern.ch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # Volume size value has no effect and is ignored
      # by the driver, but must be non-zero.
      storage: 1
  storageClassName: eos
