{{- if .Values.controllerplugin.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eosxd-csi.serviceAccountName.controllerplugin" . }}
  labels:
    {{- include "eosxd-csi.controllerplugin.metaLabels" .  | nindent 4 }}
{{- end }}

