{{- range $key, $value := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  labels:
    {{- include "eosxd-csi.common.metaLabels" $ | nindent 4 }}
{{ tpl (toYaml $value) $ }}
{{- end }}
