{{- if .Values.commonStorageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.commonStorageClass.className }}
  labels:
    {{- include "eosxd-csi.common.metaLabels" .  | nindent 4 }}
provisioner: {{ .Values.csiDriverName }}
{{- end }}
